#!/bin/bash

NAME="mcot-ns_app"                                             # Name of the application
DJANGODIR=/home/mcot/Devel/mcot-ns/src                     # Django project directory
SOCKFILE=/home/mcot/Devel/mcot-ns/src/run/mcot.sock
USER=mcot
GROUP=www-data                               # the group to run as
NUM_WORKERS=3                                # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=mcot.settings       # which settings file should Django use
DJANGO_WSGI_MODULE=mcot.wsgi               # WSGI module name

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
cd $DJANGODIR
source /home/mcot/.virtualenvs/mcot/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec /home/mcot/.virtualenvs/mcot/bin/gunicorn  ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --log-level=debug \
  --bind=unix:$SOCKFILE
